### ISSUE TITLE
Allow collection wrappers

### ISSUE THREAD

**Issue by thehpi** [orien/bean-matchers#115]
Hi,

If a collection is used, eg. Set and in my getter I wrap the collection like

    return new HashSet<>(this.set);

Then this produces an exception when `assertThatIsProperBean` is called.
The underlying reason is that it uses Mockito to create a mock but later, when it iterates the set it uses set.iterator() which returns null and causes a NullPointerException.

It sounds like you need a ValueGenerator for collections.

**Comment by orien** [comment]
Fixed in #116.
