### ISSUE TITLE
Bean setter setting another property by mistake is not tested

### ISSUE THREAD

**Issue by mobasherswl** [orien/bean-matchers#20]
`class Foo {
  private String field1;
  private String field2;

 //Given no arg constructor & all setters are present except one setter which has the issue
  public void setField1(String value) {
    field1=value;
    field2=value;
  }
}`

If the above class is tested then library fails to identify this issue. Please correct me if I have missed something

**Comment by orien** [comment]
Yes, the behaviour you have described may or may not be correct, depending on your problem domain. ie. for some properties it would be correct, and for others incorrect.

I don't think this generic tool can assert that such a behaviour is a defect.
