### ISSUE TITLE
toString detector do not find a field

### ISSUE THREAD

**Issue by gualtierotesta** [orien/bean-matchers#7]
Hi,

the hasValidBeanToString() fails on a field named **aStr** (it seems it looks for **AStr** instead).

Java version: 1.8.0_112, vendor: Oracle Corporation
BeanMatchers: 0.10

Message is 
```
java.lang.AssertionError: 
Expected: (bean class with a valid no-args constructor and bean with valid setter and getter methods for all properties and bean with all properties influencing hashCode and bean with all properties compared in equals and bean with toString() describing class name and all properties)
     but: bean with toString() describing class name and all properties bean of type "it.gualtierotesta.testsolutions.general.beans.LombokBean" had an invalid toString() method. It did not produce the property name "AStr", actual output "LombokBean(aStr=69cea64a-a26b-479c-87ca-f1626677bf54, anInt=0)"
```

Class code:
```
@Data
public class LombokBean implements Serializable {

    String aStr;
    int anInt;

}
```

Test class code:
```
 @Test
    public void testClassIsGoodBean() {
        assertThat(LombokBean.class, allOf(
                hasValidBeanConstructor(),
                hasValidGettersAndSetters(),
                hasValidBeanHashCode(),
                hasValidBeanEquals(),
                hasValidBeanToString()  // Error is here !
        ));
    }
```

Complete project can be found at https://github.com/gualtierotesta/test-solutions module general class LombokBean.

Note: I know there is no meaning to test Lombok generated toString() method but may be the problem will raise also on non Lombok generated toString methods.

**Comment by orien** [comment]
Hi @gualtierotesta, thank you for taking the time to submit this very clear defect report.

Bean-matchers delegates the identification of bean properties to the `java.beans.Introspector` class from the standard library via the [`getBeanInfo`](https://docs.oracle.com/javase/8/docs/api/java/beans/Introspector.html#getBeanInfo-java.lang.Class-) method. Unfortunately, this method has surprising behaviour when processing your  Lombok bean. Consider the following script and its output:

```java
System.out.println("GoodBean");
java.beans.BeanInfo beanInfo = java.beans.Introspector.getBeanInfo(GoodBean.class);
for(java.beans.PropertyDescriptor descriptor : beanInfo.getPropertyDescriptors()) {
    System.out.println(descriptor.getName());
}

System.out.println("LombokBean");
beanInfo = java.beans.Introspector.getBeanInfo(LombokBean.class);
for(java.beans.PropertyDescriptor descriptor : beanInfo.getPropertyDescriptors()) {
    System.out.println(descriptor.getName());
}
```
```
GoodBean
aStr
anInt
class
LombokBean
AStr
anInt
class
```
I'm not sure why the JDK names the LombokBean property `AStr` but it is outside the scope of the Bean Matchers library.

I think it's worth raising an issue on https://github.com/rzwitserloot/lombok or even the JDK.
